orbs:
  node: circleci/node@4.1
  eb: circleci/aws-elastic-beanstalk@2.0.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - eb/deploy:
          context: aws-creds
          application-name: react-docker
          environment-name: Reactdocker-env
          filters:
            branches:
              only:
                - master
          label: my-app-name-source-<<pipeline.number>>
