version: '2.1'
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

workflows:
  elastic-beanstalk-workflow:
    jobs:
      - aws-elastic-beanstalk/deploy:
          context: aws-creds
          environment-name: Reactsampleapplicationfinal-env
          application-name: react-sample-application-final
